import homeAndOffice from '../../images/workspace 1.png';
import homeImprovement from '../../images/improvement 1.png';
import homeRental from '../../images/rental 1.png';
import educationAndTraining from '../../images/education 1.png';
import itAndPlacement from '../../images/technical-support 1.png';
import jobANdConsultency from '../../images/interview 1.png';
import carRentalAndSerive from '../../images/maintenance 1.png';
import weddingService from '../../images/rings 1.png';
import deliveryService from '../../images/grocery 1.png';
import electronicsService from '../../images/electronic-device 1.png';

export const servicesData = [
  {
    id: 1,
    service: 'Home & Office',
    image: homeAndOffice,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 2,
    service: 'Home Improvement',
    image: homeImprovement,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 3,
    service: 'Home Rental',
    image: homeRental,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 4,
    service: 'Education & Training',
    image: educationAndTraining,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 5,
    service: 'IT & Placement',
    image: itAndPlacement,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 6,
    service: 'Job & Consultency',
    image: jobANdConsultency,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 7,
    service: 'Car Rental & Service',
    image: carRentalAndSerive,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 8,
    service: 'Wedding Service',
    image: weddingService,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 9,
    service: 'Delivery Service',
    image: deliveryService,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
  {
    id: 10,
    service: 'Electronics Service',
    image: electronicsService,
    submenu: [
      {
        menuLabel: 'Job Training',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Coaching & Tution',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'School / College',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Study Abroad',
        menuLinks: [
          'Big Kahuna Burger Ltd.',
          'Binford Ltd.',
          'Binford Ltd.',
          'Biffco Enterprises Ltd.',
          'Acme Co.',
          'Barone LLC.',
          'Abstergo Ltd.',
          'Abstergo Ltd.',
        ],
      },
      {
        menuLabel: 'Computer Training',
        menuLinks: [],
      },
    ],
  },
];
