import locationIcon from '../../images/svg/location.svg';
import profileIcon from '../../images/svg/profile.svg';
import homeOne from '../../images/service-one.png';
import homeTwo from '../../images/service-two.png';
import homeThree from '../../images/service-three.png';
import homeFour from '../../images/service-zero.png';
import carOne from '../../images/service-four.png';
import carTwo from '../../images/service-five.png';
import carThree from '../../images/service-six.png';
import carFour from '../../images/service-zero.png';
import itOne from '../../images/service-seven.png';
import itTwo from '../../images/service-eight.png';
import itThree from '../../images/service-nine.png';
import itFour from '../../images/service-zero.png';

export const sliderData = [
  {
    id: 1,
    serviceType: 'Home services',
    servicesAvilable: [
      {
        id: 1,
        image: [homeOne, homeTwo, homeThree, homeFour],
        title: 'Cleaning service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 2,
        image: [homeTwo, homeThree, homeFour, homeOne],
        title: 'Carpenting service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 3,
        image: [homeThree, homeFour, homeOne, homeTwo],
        title: 'Constuction service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
    ],
  },
  {
    id: 2,
    serviceType: 'Car services',
    servicesAvilable: [
      {
        id: 1,
        image: [carOne, carTwo, carThree, carFour],
        title: 'Cleaning service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 2,
        image: [carTwo, carThree, carFour, carOne],
        title: 'Carpenting service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 3,
        image: [carThree, carFour, carOne, carTwo],
        title: 'Constuction service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
    ],
  },
  {
    id: 3,
    serviceType: 'IT training',
    servicesAvilable: [
      {
        id: 1,
        image: [itOne, itTwo, itThree, itFour],
        title: 'Cleaning service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 2,
        image: [itTwo, itThree, itFour, itOne],
        title: 'Carpenting service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
      {
        id: 3,
        image: [itThree, itFour, itOne, itTwo],
        title: 'Constuction service',
        time: 'Sun-fri (08:00-22:00)',
        locationIcon: locationIcon,
        location: 'Calafornia, USA',
        profileIcon: profileIcon,
        name: 'Lara Jones',

        serviceClose: 'Sunday',
        serviceOpen: '9.00 pm',
        serviceDetails:
          'Hello, I am a full-stack web developer with 2+ years of experience with modern technologies like React JS, Next JS, Tailwind CSS, and all the other related technologies',
        offeredServices: [
          'React js, single page application',
          'Next js, server-side rendered application',
          'Static site using next js',
          'Tailwind Css',
          'Responsive design',
          'Redux',
          'React form with Formik and Yup',
          'React table with searching, pagination, sorting, filtering',
          'Material UI',
          'Typescript',
          'Firebase',
          'Framer Motion',
          'Add new features to an existing project',
        ],
        extraServices: [
          'Backend or Rest API implementation with node js, express, graphql with MongoDB or MySQL',
          'Third-party API implementation',
          'Adding a new API in your existing node js project',
        ],
        whyUs: [
          'Designing or Developing a website is not the end of the world, there is always more',
          'From optimizing the speed and performance to the best user experience and security. I care about all those things',
          'Clean code with proper commenting',
          'Reusable component',
          '100% client satisfaction',
          'Money-back guarantee',
        ],
      },
    ],
  },
];
