export const allServicesData = {
  'Home & Office': [
    {
      id: 1,
      service_type: 'Cleaning Services',
      service_item_1: 'Store room cleaning',
      service_item_2: 'Air Duct Cleaning Service',
      service_item_3: 'Appartment cleaning service',
      service_item_4: 'Carpet cleaning service',
      service_item_5: 'Window Cleaning Services',
      service_item_6: 'Furniture Cleaning Services',
      service_item_7: 'House cleaning service',
      service_item_8: 'Upholstery Cleaning Services',
      service_item_9: 'Industrial Cleaning Services',
    },
    {
      id: 2,
      service_type: 'Building Supplies And Materials',
      service_item_1: 'Store room cleaning',
      service_item_2: 'Flooring Service',
      service_item_3: 'Building Renovation Contractor',
      service_item_4: 'Roofing Specialist',
      service_item_5: 'Drywall Contractors',
      service_item_6: 'Lighting Fixtures',
      service_item_7: 'Pipeline contractors',
      service_item_8: 'Commercial Contractors',
      service_item_9: 'Sign Shops',
    },
  ],
  'Car Rental Service': [
    {
      id: 1,
      service_type: 'Cleaning Services',
      service_item_1: 'Store room cleaning',
      service_item_2: 'Air Duct Cleaning Service',
      service_item_3: 'Appartment cleaning service',
      service_item_4: 'Carpet cleaning service',
      service_item_5: 'Window Cleaning Services',
      service_item_6: 'Furniture Cleaning Services',
      service_item_7: 'House cleaning service',
      service_item_8: 'Upholstery Cleaning Services',
      service_item_9: 'Industrial Cleaning Services',
    },
    {
      id: 2,
      service_type: 'Another Services',
      service_item_1: 'Ventilation & Window Contractors',
      service_item_2: 'Air Duct Cleaning Service',
      service_item_3: 'Appartment cleaning service',
      service_item_4: 'Carpet cleaning service',
      service_item_5: 'Window Cleaning Services',
      service_item_6: 'Furniture Cleaning Services',
      service_item_7: 'House cleaning service',
      service_item_8: 'Upholstery Cleaning Services',
      service_item_9: 'Industrial Cleaning Services',
    },
  ],

  'Food & Restaurant': [
    {
      id: 1,
      service_type: 'Restaurants',
      service_item_1: 'Asian Restaurants',
      service_item_2: 'Delivery Restaurants',
      service_item_3: 'South Indian Restaurants',
      service_item_4: 'North Indian Restaurants',
      service_item_5: 'Vegetarian Restaurants',
      service_item_6: 'Brazilian Cuisine Restaurants',
      service_item_7: 'Continental Restaurants',
      service_item_8: 'European Restaurants',
      service_item_9: 'Hot Dog Joints',
    },
    {
      id: 2,
      service_type: 'Food/Meal',
      service_item_1: 'Store room cleaning',
      service_item_2: 'Air Duct Cleaning Service',
      service_item_3: 'Appartment cleaning service',
      service_item_4: 'Carpet cleaning service',
      service_item_5: 'Window Cleaning Services',
      service_item_6: 'Furniture Cleaning Services',
      service_item_7: 'House cleaning service',
      service_item_8: 'Upholstery Cleaning Services',
      service_item_9: 'Industrial Cleaning Services',
    },
  ],
};
