import homeAndOffice from '../../images/workspace 1.png';
import carRentalService from '../../images/maintenance 1.png';
import foodAndRestaurant from '../../images/grocery 1.png';

export const allServicesData = [
  {
    serType: 'Home & Office',
    serIcon: homeAndOffice,
    serAvailabe: [
      {
        serSubType: 'Cleaning Services',
        serItem1: 'Store room cleaning',
        serItem2: 'Air Duct Cleaning Service',
        serItem3: 'Appartment cleaning service',
        serItem4: 'Carpet cleaning service',
        serItem5: 'Window Cleaning Services',
        serItem6: 'Furniture Cleaning Services',
        serItem7: 'House cleaning service',
        serItem8: 'Upholstery Cleaning Services',
        serItem9: 'Industrial Cleaning Services',
      },
      {
        serSubType: 'Building Supplies And Materials',
        serItem1: 'Store room cleaning',
        serItem2: 'Flooring Service',
        serItem3: 'Building Renovation Contractor',
        serItem4: 'Roofing Specialist',
        serItem5: 'Drywall Contractors',
        serItem6: 'Lighting Fixtures',
        serItem7: 'Pipeline contractors',
        serItem8: 'Commercial Contractors',
        serItem9: 'Sign Shops',
      },
    ],
  },
  {
    serType: 'Car Rental Service',
    serIcon: carRentalService,
    serAvailabe: [
      {
        serSubType: 'Cleaning Services',
        serItem1: 'Store room cleaning',
        serItem2: 'Air Duct Cleaning Service',
        serItem3: 'Appartment cleaning service',
        serItem4: 'Carpet cleaning service',
        serItem5: 'Window Cleaning Services',
        serItem6: 'Furniture Cleaning Services',
        serItem7: 'House cleaning service',
        serItem8: 'Upholstery Cleaning Services',
        serItem9: 'Industrial Cleaning Services',
      },
      {
        serSubType: 'Another Services',
        serItem1: 'Ventilation & Window Contractors',
        serItem2: 'Air Duct Cleaning Service',
        serItem3: 'Appartment cleaning service',
        serItem4: 'Carpet cleaning service',
        serItem5: 'Window Cleaning Services',
        serItem6: 'Furniture Cleaning Services',
        serItem7: 'House cleaning service',
        serItem8: 'Upholstery Cleaning Services',
        serItem9: 'Industrial Cleaning Services',
      },
    ],
  },
  {
    serType: 'Food & Restaurant',
    serIcon: foodAndRestaurant,
    serAvailabe: [
      {
        serSubType: 'Restaurants',
        serItem1: 'Asian Restaurants',
        serItem2: 'Delivery Restaurants',
        serItem3: 'South Indian Restaurants',
        serItem4: 'North Indian Restaurants',
        serItem5: 'Vegetarian Restaurants',
        serItem6: 'Brazilian Cuisine Restaurants',
        serItem7: 'Continental Restaurants',
        serItem8: 'European Restaurants',
        serItem9: 'Hot Dog Joints',
      },
      {
        serSubType: 'Food/Meal',
        serItem1: 'Store room cleaning',
        serItem2: 'Air Duct Cleaning Service',
        serItem3: 'Appartment cleaning service',
        serItem4: 'Carpet cleaning service',
        serItem5: 'Window Cleaning Services',
        serItem6: 'Furniture Cleaning Services',
        serItem7: 'House cleaning service',
        serItem8: 'Upholstery Cleaning Services',
        serItem9: 'Industrial Cleaning Services',
      },
    ],
  },
];
